# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: php:7.3-fpm-alpine

pipelines:
  default:
    - step:
        caches:
          - node
        name: "Build and test JS"
        image: node:10.16.3
        script:
          - npm install
          - npm test
          - npm run build