<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20200111073334 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        //changed all of them for safety

        $this->addSql('CREATE TABLE countries (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cities (id INT AUTO_INCREMENT NOT NULL, country_id INT NOT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_D95DB16BF92F3E70 (country_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE users (id INT AUTO_INCREMENT NOT NULL, merchant_id INT NOT NULL, default_sector_id INT NOT NULL, first_name VARCHAR(50) NOT NULL, last_name VARCHAR(50) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) DEFAULT NULL, md5_password VARCHAR(255) DEFAULT NULL, roles JSON NOT NULL, merchant_roles JSON NOT NULL, national_id VARCHAR(11) NOT NULL, phone_number VARCHAR(20) NOT NULL, gender SMALLINT NOT NULL, date_of_birth DATETIME DEFAULT NULL, validation_code VARCHAR(10) NOT NULL, verified_at DATETIME DEFAULT NULL, ip_address VARCHAR(20) NOT NULL, is_active TINYINT(1) NOT NULL, sms_permission TINYINT(1) NOT NULL, email_permission TINYINT(1) NOT NULL, last_login_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_1483A5E9E7927C74 (email), INDEX IDX_1483A5E96796D554 (merchant_id), INDEX IDX_1483A5E94FF7E0C0 (default_sector_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE countries (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cities (id INT AUTO_INCREMENT NOT NULL, country_id INT NOT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_D95DB16BF92F3E70 (country_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE users (id INT AUTO_INCREMENT NOT NULL, merchant_id INT NOT NULL, default_sector_id INT NOT NULL, first_name VARCHAR(50) NOT NULL, last_name VARCHAR(50) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) DEFAULT NULL, md5_password VARCHAR(255) DEFAULT NULL, roles JSON NOT NULL, merchant_roles JSON NOT NULL, national_id VARCHAR(11) NOT NULL, phone_number VARCHAR(20) NOT NULL, gender SMALLINT NOT NULL, date_of_birth DATETIME DEFAULT NULL, validation_code VARCHAR(10) NOT NULL, verified_at DATETIME DEFAULT NULL, ip_address VARCHAR(20) NOT NULL, is_active TINYINT(1) NOT NULL, sms_permission TINYINT(1) NOT NULL, email_permission TINYINT(1) NOT NULL, last_login_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_1483A5E9E7927C74 (email), INDEX IDX_1483A5E96796D554 (merchant_id), INDEX IDX_1483A5E94FF7E0C0 (default_sector_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE countries (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cities (id INT AUTO_INCREMENT NOT NULL, country_id INT NOT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_D95DB16BF92F3E70 (country_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE users (id INT AUTO_INCREMENT NOT NULL, merchant_id INT NOT NULL, default_sector_id INT NOT NULL, first_name VARCHAR(50) NOT NULL, last_name VARCHAR(50) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) DEFAULT NULL, md5_password VARCHAR(255) DEFAULT NULL, roles JSON NOT NULL, merchant_roles JSON NOT NULL, national_id VARCHAR(11) NOT NULL, phone_number VARCHAR(20) NOT NULL, gender SMALLINT NOT NULL, date_of_birth DATETIME DEFAULT NULL, validation_code VARCHAR(10) NOT NULL, verified_at DATETIME DEFAULT NULL, ip_address VARCHAR(20) NOT NULL, is_active TINYINT(1) NOT NULL, sms_permission TINYINT(1) NOT NULL, email_permission TINYINT(1) NOT NULL, last_login_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_1483A5E9E7927C74 (email), INDEX IDX_1483A5E96796D554 (merchant_id), INDEX IDX_1483A5E94FF7E0C0 (default_sector_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE countries (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cities (id INT AUTO_INCREMENT NOT NULL, country_id INT NOT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_D95DB16BF92F3E70 (country_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE users (id INT AUTO_INCREMENT NOT NULL, merchant_id INT NOT NULL, default_sector_id INT NOT NULL, first_name VARCHAR(50) NOT NULL, last_name VARCHAR(50) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) DEFAULT NULL, md5_password VARCHAR(255) DEFAULT NULL, roles JSON NOT NULL, merchant_roles JSON NOT NULL, national_id VARCHAR(11) NOT NULL, phone_number VARCHAR(20) NOT NULL, gender SMALLINT NOT NULL, date_of_birth DATETIME DEFAULT NULL, validation_code VARCHAR(10) NOT NULL, verified_at DATETIME DEFAULT NULL, ip_address VARCHAR(20) NOT NULL, is_active TINYINT(1) NOT NULL, sms_permission TINYINT(1) NOT NULL, email_permission TINYINT(1) NOT NULL, last_login_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_1483A5E9E7927C74 (email), INDEX IDX_1483A5E96796D554 (merchant_id), INDEX IDX_1483A5E94FF7E0C0 (default_sector_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE countries (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cities (id INT AUTO_INCREMENT NOT NULL, country_id INT NOT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_D95DB16BF92F3E70 (country_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE users (id INT AUTO_INCREMENT NOT NULL, merchant_id INT NOT NULL, default_sector_id INT NOT NULL, first_name VARCHAR(50) NOT NULL, last_name VARCHAR(50) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) DEFAULT NULL, md5_password VARCHAR(255) DEFAULT NULL, roles JSON NOT NULL, merchant_roles JSON NOT NULL, national_id VARCHAR(11) NOT NULL, phone_number VARCHAR(20) NOT NULL, gender SMALLINT NOT NULL, date_of_birth DATETIME DEFAULT NULL, validation_code VARCHAR(10) NOT NULL, verified_at DATETIME DEFAULT NULL, ip_address VARCHAR(20) NOT NULL, is_active TINYINT(1) NOT NULL, sms_permission TINYINT(1) NOT NULL, email_permission TINYINT(1) NOT NULL, last_login_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_1483A5E9E7927C74 (email), INDEX IDX_1483A5E96796D554 (merchant_id), INDEX IDX_1483A5E94FF7E0C0 (default_sector_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE countries (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cities (id INT AUTO_INCREMENT NOT NULL, country_id INT NOT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_D95DB16BF92F3E70 (country_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE users (id INT AUTO_INCREMENT NOT NULL, merchant_id INT NOT NULL, default_sector_id INT NOT NULL, first_name VARCHAR(50) NOT NULL, last_name VARCHAR(50) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) DEFAULT NULL, md5_password VARCHAR(255) DEFAULT NULL, roles JSON NOT NULL, merchant_roles JSON NOT NULL, national_id VARCHAR(11) NOT NULL, phone_number VARCHAR(20) NOT NULL, gender SMALLINT NOT NULL, date_of_birth DATETIME DEFAULT NULL, validation_code VARCHAR(10) NOT NULL, verified_at DATETIME DEFAULT NULL, ip_address VARCHAR(20) NOT NULL, is_active TINYINT(1) NOT NULL, sms_permission TINYINT(1) NOT NULL, email_permission TINYINT(1) NOT NULL, last_login_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_1483A5E9E7927C74 (email), INDEX IDX_1483A5E96796D554 (merchant_id), INDEX IDX_1483A5E94FF7E0C0 (default_sector_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE countries (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cities (id INT AUTO_INCREMENT NOT NULL, country_id INT NOT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_D95DB16BF92F3E70 (country_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE users (id INT AUTO_INCREMENT NOT NULL, merchant_id INT NOT NULL, default_sector_id INT NOT NULL, first_name VARCHAR(50) NOT NULL, last_name VARCHAR(50) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) DEFAULT NULL, md5_password VARCHAR(255) DEFAULT NULL, roles JSON NOT NULL, merchant_roles JSON NOT NULL, national_id VARCHAR(11) NOT NULL, phone_number VARCHAR(20) NOT NULL, gender SMALLINT NOT NULL, date_of_birth DATETIME DEFAULT NULL, validation_code VARCHAR(10) NOT NULL, verified_at DATETIME DEFAULT NULL, ip_address VARCHAR(20) NOT NULL, is_active TINYINT(1) NOT NULL, sms_permission TINYINT(1) NOT NULL, email_permission TINYINT(1) NOT NULL, last_login_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_1483A5E9E7927C74 (email), INDEX IDX_1483A5E96796D554 (merchant_id), INDEX IDX_1483A5E94FF7E0C0 (default_sector_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE countries (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cities (id INT AUTO_INCREMENT NOT NULL, country_id INT NOT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_D95DB16BF92F3E70 (country_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE users (id INT AUTO_INCREMENT NOT NULL, merchant_id INT NOT NULL, default_sector_id INT NOT NULL, first_name VARCHAR(50) NOT NULL, last_name VARCHAR(50) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) DEFAULT NULL, md5_password VARCHAR(255) DEFAULT NULL, roles JSON NOT NULL, merchant_roles JSON NOT NULL, national_id VARCHAR(11) NOT NULL, phone_number VARCHAR(20) NOT NULL, gender SMALLINT NOT NULL, date_of_birth DATETIME DEFAULT NULL, validation_code VARCHAR(10) NOT NULL, verified_at DATETIME DEFAULT NULL, ip_address VARCHAR(20) NOT NULL, is_active TINYINT(1) NOT NULL, sms_permission TINYINT(1) NOT NULL, email_permission TINYINT(1) NOT NULL, last_login_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_1483A5E9E7927C74 (email), INDEX IDX_1483A5E96796D554 (merchant_id), INDEX IDX_1483A5E94FF7E0C0 (default_sector_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE countries (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cities (id INT AUTO_INCREMENT NOT NULL, country_id INT NOT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_D95DB16BF92F3E70 (country_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE users (id INT AUTO_INCREMENT NOT NULL, merchant_id INT NOT NULL, default_sector_id INT NOT NULL, first_name VARCHAR(50) NOT NULL, last_name VARCHAR(50) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) DEFAULT NULL, md5_password VARCHAR(255) DEFAULT NULL, roles JSON NOT NULL, merchant_roles JSON NOT NULL, national_id VARCHAR(11) NOT NULL, phone_number VARCHAR(20) NOT NULL, gender SMALLINT NOT NULL, date_of_birth DATETIME DEFAULT NULL, validation_code VARCHAR(10) NOT NULL, verified_at DATETIME DEFAULT NULL, ip_address VARCHAR(20) NOT NULL, is_active TINYINT(1) NOT NULL, sms_permission TINYINT(1) NOT NULL, email_permission TINYINT(1) NOT NULL, last_login_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_1483A5E9E7927C74 (email), INDEX IDX_1483A5E96796D554 (merchant_id), INDEX IDX_1483A5E94FF7E0C0 (default_sector_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE countries (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cities (id INT AUTO_INCREMENT NOT NULL, country_id INT NOT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_D95DB16BF92F3E70 (country_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE users (id INT AUTO_INCREMENT NOT NULL, merchant_id INT NOT NULL, default_sector_id INT NOT NULL, first_name VARCHAR(50) NOT NULL, last_name VARCHAR(50) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) DEFAULT NULL, md5_password VARCHAR(255) DEFAULT NULL, roles JSON NOT NULL, merchant_roles JSON NOT NULL, national_id VARCHAR(11) NOT NULL, phone_number VARCHAR(20) NOT NULL, gender SMALLINT NOT NULL, date_of_birth DATETIME DEFAULT NULL, validation_code VARCHAR(10) NOT NULL, verified_at DATETIME DEFAULT NULL, ip_address VARCHAR(20) NOT NULL, is_active TINYINT(1) NOT NULL, sms_permission TINYINT(1) NOT NULL, email_permission TINYINT(1) NOT NULL, last_login_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_1483A5E9E7927C74 (email), INDEX IDX_1483A5E96796D554 (merchant_id), INDEX IDX_1483A5E94FF7E0C0 (default_sector_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE countries (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cities (id INT AUTO_INCREMENT NOT NULL, country_id INT NOT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_D95DB16BF92F3E70 (country_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE users (id INT AUTO_INCREMENT NOT NULL, merchant_id INT NOT NULL, default_sector_id INT NOT NULL, first_name VARCHAR(50) NOT NULL, last_name VARCHAR(50) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) DEFAULT NULL, md5_password VARCHAR(255) DEFAULT NULL, roles JSON NOT NULL, merchant_roles JSON NOT NULL, national_id VARCHAR(11) NOT NULL, phone_number VARCHAR(20) NOT NULL, gender SMALLINT NOT NULL, date_of_birth DATETIME DEFAULT NULL, validation_code VARCHAR(10) NOT NULL, verified_at DATETIME DEFAULT NULL, ip_address VARCHAR(20) NOT NULL, is_active TINYINT(1) NOT NULL, sms_permission TINYINT(1) NOT NULL, email_permission TINYINT(1) NOT NULL, last_login_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_1483A5E9E7927C74 (email), INDEX IDX_1483A5E96796D554 (merchant_id), INDEX IDX_1483A5E94FF7E0C0 (default_sector_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE countries (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cities (id INT AUTO_INCREMENT NOT NULL, country_id INT NOT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_D95DB16BF92F3E70 (country_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE users (id INT AUTO_INCREMENT NOT NULL, merchant_id INT NOT NULL, default_sector_id INT NOT NULL, first_name VARCHAR(50) NOT NULL, last_name VARCHAR(50) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) DEFAULT NULL, md5_password VARCHAR(255) DEFAULT NULL, roles JSON NOT NULL, merchant_roles JSON NOT NULL, national_id VARCHAR(11) NOT NULL, phone_number VARCHAR(20) NOT NULL, gender SMALLINT NOT NULL, date_of_birth DATETIME DEFAULT NULL, validation_code VARCHAR(10) NOT NULL, verified_at DATETIME DEFAULT NULL, ip_address VARCHAR(20) NOT NULL, is_active TINYINT(1) NOT NULL, sms_permission TINYINT(1) NOT NULL, email_permission TINYINT(1) NOT NULL, last_login_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_1483A5E9E7927C74 (email), INDEX IDX_1483A5E96796D554 (merchant_id), INDEX IDX_1483A5E94FF7E0C0 (default_sector_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');


    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        // TABLE DROP COMMANDS
    }
}
